/**
 * Auth routes — OTP-based phone login backed by SQLite.
 *
 * POST /auth/otp-request  — request OTP (dev: logs to console, prod: SMS)
 * POST /auth/login        — verify OTP + issue JWT pair, create user if new
 * POST /auth/refresh      — exchange refresh token for new access token
 * POST /auth/logout       — revoke refresh token
 */

import { Hono } from "hono";
import { zValidator } from "@hono/zod-validator";
import { z } from "zod";
import { randomInt } from "node:crypto";
import { LoginRequestSchema, LoginResponseSchema } from "../models/schemas.js";
import { signAccessToken, signRefreshToken, verifyToken } from "../lib/auth.js";
import {
  createOtp,
  verifyOtpDev,
  verifyAndConsumeOtp,
  storeRefreshToken,
  validateRefreshToken,
  revokeRefreshToken,
} from "../db/repos/auth.js";
import { findUserByPhone, createUser, findUserById } from "../db/repos/users.js";
import { createWallet, findWalletByUserId } from "../db/repos/wallet.js";

/**
 * Dev OTP shortcut (accept any 6-digit code) is ONLY enabled when the explicit
 * AUTH_DEV_OTP=true flag is set AND we are not running in production. Production
 * always falls through to the strict verifyAndConsumeOtp path. This closes the
 * auth bypass where any 6-digit code logged in as any phone (VUU-78).
 */
function isDevOtpEnabled(): boolean {
  return process.env["AUTH_DEV_OTP"] === "true" && process.env["NODE_ENV"] !== "production";
}

/**
 * Generate the OTP code for a request. In dev mode we use the fixed 123456 so
 * local/test flows are predictable; otherwise we generate a cryptographically
 * random 6-digit code that an attacker cannot guess (the login path only
 * accepts this exact code, single-use, within 300s).
 */
function generateOtpCode(): string {
  if (isDevOtpEnabled()) return "123456";
  return String(randomInt(0, 1_000_000)).padStart(6, "0");
}

export const authRouter = new Hono();

// POST /auth/otp-request
authRouter.post("/otp-request", zValidator("json", z.object({ phone: z.string() })), (c) => {
  const { phone } = c.req.valid("json");
  const otp = generateOtpCode();
  createOtp(phone, otp);
  // TODO: deliver via SMS servico (Twilio/AWS SNS) in production. Until then the
  // code is logged server-side only — never returned in the response.
  console.log(`[auth] OTP for ${phone}: ${otp}`);
  return c.json({ message: "OTP sent", expiresIn: 300 });
});

// POST /auth/login
authRouter.post("/login", zValidator("json", LoginRequestSchema), async (c) => {
  const { phone, otpCode } = c.req.valid("json");

  // Validate OTP. Production (and any non-dev env) requires the real, single-use,
  // unexpired code generated by /otp-request. Dev shortcut only behind AUTH_DEV_OTP.
  const otpValid = isDevOtpEnabled()
    ? verifyOtpDev(phone, otpCode)
    : verifyAndConsumeOtp(phone, otpCode);
  if (!otpValid) {
    return c.json({ code: "INVALID_OTP", message: "Invalid or expired OTP code" }, 400);
  }

  let user = findUserByPhone(phone);
  if (!user) {
    // Auto-register as passenger on first login
    user = createUser({
      fullName: "Novo Usuário",
      email: `${phone.replace(/\D/g, "")}@vuup.app`,
      phone,
      role: "passenger",
      status: "active",
    });
    // Create associated wallet
    if (!findWalletByUserId(user.id)) {
      createWallet(user.id, 0);
    }
  }

  const [accessToken, refreshToken] = await Promise.all([
    signAccessToken(user.id, user.role),
    signRefreshToken(user.id),
  ]);

  // Persist refresh token
  storeRefreshToken(refreshToken, user.id);

  const response = LoginResponseSchema.parse({
    accessToken,
    refreshToken,
    expiresIn: 900,
    user: {
      id: user.id,
      fullName: user.fullName,
      avatarUrl: user.avatarUrl,
      rating: user.rating,
      role: user.role,
    },
  });

  return c.json(response, 200);
});

// POST /auth/refresh
authRouter.post(
  "/refresh",
  zValidator("json", z.object({ refreshToken: z.string() })),
  async (c) => {
    const { refreshToken } = c.req.valid("json");

    // First verify JWT signature/expiry
    let userId: string;
    try {
      const payload = await verifyToken(refreshToken);
      userId = payload.sub ?? "";
    } catch {
      return c.json({ code: "INVALID_TOKEN", message: "Refresh token invalid or expired" }, 401);
    }

    // Then check DB revocation
    const record = validateRefreshToken(refreshToken);
    if (!record) {
      return c.json({ code: "TOKEN_REVOKED", message: "Refresh token has been revoked" }, 401);
    }

    const user = findUserById(userId);
    if (!user) {
      return c.json({ code: "USER_NOT_FOUND", message: "User no longer exists" }, 401);
    }

    const accessToken = await signAccessToken(userId, user.role);
    return c.json({ accessToken, expiresIn: 900 });
  },
);

// POST /auth/logout
authRouter.post(
  "/logout",
  zValidator("json", z.object({ refreshToken: z.string().optional() })),
  (c) => {
    const { refreshToken } = c.req.valid("json");
    if (refreshToken) {
      revokeRefreshToken(refreshToken);
    }
    return c.json({ message: "Logged out" });
  },
);
