/**
 * VUU-78 — auth bypass regression tests.
 *
 * Verifies the strict production OTP path on POST /auth/login: only the real
 * code generated by /auth/otp-request is accepted, it is single-use, and it
 * expires. The dev shortcut (accept any 6-digit code) is disabled here by
 * forcing AUTH_DEV_OTP off, so these tests exercise verifyAndConsumeOtp — the
 * exact path that runs in production.
 */

import { describe, it, expect, beforeAll, afterAll } from "vitest";
import app from "../index.js";
import { createOtp } from "../db/repos/auth.js";
import db from "../db/database.js";

const PHONE = "+5511970000123";

let prevDevOtp: string | undefined;

beforeAll(() => {
  // Force the strict (production) OTP path regardless of vitest defaults.
  prevDevOtp = process.env["AUTH_DEV_OTP"];
  delete process.env["AUTH_DEV_OTP"];
});

afterAll(() => {
  if (prevDevOtp === undefined) delete process.env["AUTH_DEV_OTP"];
  else process.env["AUTH_DEV_OTP"] = prevDevOtp;
});

async function login(phone: string, otpCode: string): Promise<Response> {
  return app.request("/auth/login", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ phone, otpCode }),
  });
}

describe("POST /auth/login — strict OTP (VUU-78 bypass guard)", () => {
  it("rejects a random 6-digit code for a phone that never requested an OTP", async () => {
    const res = await login("+5511988887777", "999999");
    expect(res.status).toBe(400);
    const body = (await res.json()) as { code?: string };
    expect(body.code).toBe("INVALID_OTP");
  });

  it("rejects a wrong code when an OTP exists for the phone", async () => {
    createOtp(PHONE, "111111");
    const res = await login(PHONE, "222222");
    expect(res.status).toBe(400);
  });

  it("accepts the correct code exactly once (single-use)", async () => {
    createOtp(PHONE, "654321");

    const first = await login(PHONE, "654321");
    expect(first.status).toBe(200);
    const body = (await first.json()) as { accessToken?: string };
    expect(body.accessToken).toBeTruthy();

    // Replaying the same consumed code must now fail.
    const second = await login(PHONE, "654321");
    expect(second.status).toBe(400);
  });

  it("rejects an expired code", async () => {
    // Insert an already-expired OTP directly.
    const past = new Date(Date.now() - 1000).toISOString();
    db.prepare(
      `INSERT INTO otp_codes (id, phone, code, expires_at, used, created_at)
       VALUES (?, ?, ?, ?, 0, ?)`,
    ).run("expired-otp-1", PHONE, "777777", past, new Date().toISOString());

    const res = await login(PHONE, "777777");
    expect(res.status).toBe(400);
  });

  it("does not return the OTP code in the /auth/otp-request response", async () => {
    const res = await app.request("/auth/otp-request", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ phone: "+5511960000999" }),
    });
    expect(res.status).toBe(200);
    const text = await res.text();
    // Response must not leak any 6-digit code to the caller.
    expect(/\b\d{6}\b/.test(text)).toBe(false);
  });
});
