/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WowRouteImport } from './routes/wow'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as SafetyRouteImport } from './routes/safety'
import { Route as RidesRouteImport } from './routes/rides'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as IndexRouteImport } from './routes/index'

const WowRoute = WowRouteImport.update({
  id: '/wow',
  path: '/wow',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyRoute = SafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => rootRouteImport,
} as any)
const RidesRoute = RidesRouteImport.update({
  id: '/rides',
  path: '/rides',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/gallery': typeof GalleryRoute
  '/profile': typeof ProfileRoute
  '/rides': typeof RidesRoute
  '/safety': typeof SafetyRoute
  '/wallet': typeof WalletRoute
  '/wow': typeof WowRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/gallery': typeof GalleryRoute
  '/profile': typeof ProfileRoute
  '/rides': typeof RidesRoute
  '/safety': typeof SafetyRoute
  '/wallet': typeof WalletRoute
  '/wow': typeof WowRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/gallery': typeof GalleryRoute
  '/profile': typeof ProfileRoute
  '/rides': typeof RidesRoute
  '/safety': typeof SafetyRoute
  '/wallet': typeof WalletRoute
  '/wow': typeof WowRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/gallery' | '/profile' | '/rides' | '/safety' | '/wallet' | '/wow'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/gallery' | '/profile' | '/rides' | '/safety' | '/wallet' | '/wow'
  id:
    | '__root__'
    | '/'
    | '/gallery'
    | '/profile'
    | '/rides'
    | '/safety'
    | '/wallet'
    | '/wow'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GalleryRoute: typeof GalleryRoute
  ProfileRoute: typeof ProfileRoute
  RidesRoute: typeof RidesRoute
  SafetyRoute: typeof SafetyRoute
  WalletRoute: typeof WalletRoute
  WowRoute: typeof WowRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wow': {
      id: '/wow'
      path: '/wow'
      fullPath: '/wow'
      preLoaderRoute: typeof WowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety': {
      id: '/safety'
      path: '/safety'
      fullPath: '/safety'
      preLoaderRoute: typeof SafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rides': {
      id: '/rides'
      path: '/rides'
      fullPath: '/rides'
      preLoaderRoute: typeof RidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GalleryRoute: GalleryRoute,
  ProfileRoute: ProfileRoute,
  RidesRoute: RidesRoute,
  SafetyRoute: SafetyRoute,
  WalletRoute: WalletRoute,
  WowRoute: WowRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
